# Generated by Django 4.2 on 2023-09-07 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prayer_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='title',
        ),
        migrations.AddField(
            model_name='prayer',
            name='topic',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prayer_App.prayertopic'),
        ),
    ]
