# Generated by Django 4.2 on 2023-09-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prayer_App', '0002_prayertopic_remove_prayer_title_prayer_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayer',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='prayertopic',
            name='confession',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='Prayer_App.prayertopic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prayertopic',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
