# Generated by Django 4.2 on 2023-09-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prayer_App', '0003_rename_content_prayer_text_prayertopic_confession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayertopic',
            name='confession',
            field=models.TextField(),
        ),
    ]
