# Generated by Django 4.2 on 2023-09-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prayer_App', '0006_remove_video_video_url_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
