# Generated by Django 4.2 on 2023-09-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prayer_App', '0007_video_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
    ]
