# Generated by Django 4.2.5 on 2023-09-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prayer_App', '0008_remove_video_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
